.github/workflows/ci.yml, .github/workflows/preview-db.yml
=> [CI/CD] Preview DBs

.github/workflows/ci.yml, .github/workflows/pr-close.yml, .github/workflows/preview-db.yml
=> ref: separate workflow

.github/workflows/ci.yml
=> ref: add Preview database dependency on ESLint action

data-dashboard/example.env, data-dashboard/next.config.js, data-dashboard/pages/api/test-env.ts
This is an infratstructure PR, it allows us to associate the different environments to our DBs.
**Note:** local development might fail because we stiil need to standarize a way to run a Postgres DB.
No associated DBs
Associated DBs per environment
No
We still need to define a workflow for local development
=> [Feature] Add dynamic database url env variable

.github/workflows/pr-close.yml
=> [Infra]: add connection removal step

data-dashboard/lib/components/TopLayout/TopLayout.tsx, data-dashboard/pages/_app.tsx, data-dashboard/pages/board/[id].tsx, data-dashboard/pages/boards.tsx, data-dashboard/pages/data-sources/index.tsx, data-dashboard/pages/signin.tsx, data-dashboard/pages/signup.tsx
- Just adds a TopLayout component that we can adjust to our needs.
- No Layout. NavBar is manually placed on every page.
- A `<TopLayout>{children}</TopLayout>` component that we can add to the pages where we need it.
This is how Layout works:
``` typescript
const SignUpPage: NextPageWithLayout = SignUp;
SignUpPage.getLayout = (page) => (
<TopLayout>
{page} …
```
=> [Feature] Add top layout component

data-dashboard/lib/components/BoardTitleModal/BoardTitleModal.tsx, data-dashboard/lib/components/InputField/InputField.tsx, data-dashboard/lib/components/ModalContainer/ModalContainer.tsx, data-dashboard/pages/boards.tsx, data-dashboard/pages/signin.tsx
=> Feat - modal create board

data-dashboard/lib/constants.ts, data-dashboard/lib/contexts/AuthContext.tsx, data-dashboard/lib/hooks/auth.ts, data-dashboard/lib/hooks/index.ts, data-dashboard/middleware.ts, data-dashboard/pages/_app.tsx, data-dashboard/pages/boards.tsx, data-dashboard/server/trpc/routers/auth.ts, pull_request_template.md
- Adds route protection to our pages
=> [Feat] Add route protection

data-dashboard/pages/data-sources/index.tsx, data-dashboard/prisma/migrations/20230527054719_/migration.sql, data-dashboard/prisma/schema.prisma, data-dashboard/server/models/dataSource.ts, data-dashboard/server/repositories/dataSource.ts, data-dashboard/server/trpc/routers/dataSources.ts
Data sources can now be accessed
=> [Feat] Add public data sources

data-dashboard/server/init.ts, data-dashboard/server/models/chart.ts, data-dashboard/server/models/index.ts, data-dashboard/server/repositories/chart.ts, data-dashboard/server/trpc/routers/charts.ts
=> [Feat] crud trpc charts

data-dashboard/lib/components/DataSourcesMenuModal/DataSourcesMenuModal.tsx
Fixes a stale reference to listDataSources query
n/a
=> [Fix] remove reference to listDataSources query

data-dashboard/lib/components/DataSourcesMenuModal/DataSourcesMenuModal.tsx
We are releasing a bunch of stuff.
=> Release #2

.github/workflows/ci.yml
- This PR changes the references in CI.yml to be triggered by events on **master**
- N/a
=> [Refactor]: change production branch references to master

data-dashboard/lib/components/BoardList/MOCK_CHART_LIST.tsx, data-dashboard/lib/components/BoardList/MOCK_CHART_PROPS.tsx, data-dashboard/lib/components/Chart/Chart.tsx, data-dashboard/lib/components/ChartCard/ChartCard.tsx, data-dashboard/lib/components/TemporalDataSourcesListModal/TemporalDataSourcesListModal.tsx, data-dashboard/pages/boards/[id].tsx, data-dashboard/server/repositories/chart.ts, data-dashboard/server/trpc/routers/_app.ts, data-dashboard/server/trpc/routers/charts.ts
=> [Feat] chart get create

data-dashboard/pages/api/upload-file.ts, data-dashboard/pages/boards/test-serializer.tsx, data-dashboard/server/init.ts, data-dashboard/server/models/chart.ts, data-dashboard/server/repositories/chart.ts, data-dashboard/server/repositories/dataSource.ts, data-dashboard/server/services/chartSerializer.ts, data-dashboard/server/trpc/routers/charts.ts
- Completes the implementation of the chart serializer service
=> [Feature] Implement chart serializer

data-dashboard/lib/utils/formValidation.ts, data-dashboard/pages/signin.tsx, data-dashboard/pages/signup.tsx, data-dashboard/styles/globals.css
Added error messages in /signup and /signin pages
Eliminated Name and Last-name fields in signup (unnecessary due to absence in backend)
Fixed signin form fields width to be consistent with other pages.
=> Added error messages on signin and signup + UI tweaks

data-dashboard/lib/components/Chart/Chart.tsx, data-dashboard/lib/components/ChartConfiguration/ChartConfiguration.tsx, data-dashboard/lib/components/ChartTypeMenu/ChartTypeMenu.tsx, data-dashboard/lib/components/CreateChartFlow/CreateChartFlow.tsx, data-dashboard/lib/components/DataSourceOrigin/DataSourceOrigin.tsx, data-dashboard/lib/components/DataSourceSelection/DataSourceSelection.tsx, data-dashboard/lib/components/DropdownInput/DropdownInput.tsx, data-dashboard/lib/components/PreviewChart/PreviewChart.tsx, data-dashboard/pages/boards/[id].tsx
=> [Pre-PR] chart flow

Makefile, data-dashboard/lib/components/ChartConfiguration/ChartConfiguration.tsx, data-dashboard/lib/components/CreateChartFlow/CreateChartFlow.tsx, data-dashboard/lib/components/DropdownInput/DropdownInput.tsx, data-dashboard/server/init.ts, data-dashboard/server/models/dataSource.ts, data-dashboard/server/services/chartSerializer.ts, data-dashboard/server/trpc/routers/dataSources.ts
- Moves the instantiation of the Prisma Client outside of the context initializer to reduce connections to our Data Base.
NA
=> ref(sever): set db instance as global variable

data-dashboard/lib/components/NavBar/NavBar.tsx, data-dashboard/server/trpc/routers/auth.ts
Small fix to delete auth-token cookie
=> [FIX] Log Out now works

data-dashboard/lib/components/ChartConfiguration/ChartConfiguration.tsx, data-dashboard/lib/components/PreviewChart/PreviewChart.tsx, data-dashboard/pages/boards/[id].tsx
=> feat: remove unhandled exception form Chart component

data-dashboard/lib/base64.ts, data-dashboard/lib/components/BoardList/BoardList.tsx, data-dashboard/lib/components/BoardPreview/BoardPreview.tsx, data-dashboard/lib/components/DataSourceSelection/DataSourceSelection.tsx, data-dashboard/lib/components/NavBar/NavBar.tsx, data-dashboard/package.json, data-dashboard/pages/boards/[id].tsx, data-dashboard/pages/boards/index.tsx, data-dashboard/prisma/migrations/20230612192556_add_preview_img_field/migration.sql, data-dashboard/prisma/schema.prisma, data-dashboard/server/models/board.ts, data-dashboard/server/repositories/board.ts, data-dashboard/server/trpc/routers/boards.ts, data-dashboard/yarn.lock
=> [Feature] Add board preview images

data-dashboard/pages/index.tsx, data-dashboard/yarn.lock
- Protects the root (`/`) route, redirecting to /boards.
=> fix: add redirect to root route

data-dashboard/middleware.ts
=> fix: exclude _next routes
